import os, sys
sys.path.insert(0, os.path.abspath('../../zot'))

import zot
zot = zot.ZotCodeGenerator()
zot.generateTestCode('SimpleGLExampleTest.cpp',
                     'SimpleGLExampleTest-gen.cpp',
                     ['../../googletest-release-1.8.0/googletest/include',
                      '../../freeglut-MSVC-3.0.0-2.mp/freeglut/include'])

env = Environment()

example_lib = env.StaticLibrary(target = 'build/Objects',
                                source = ['SimpleGLExample.cpp'],
                                CPPPATH = ['../../include',
                                           '../../freeglut-MSVC-3.0.0-2.mp/freeglut/include'])
                                                           
test_objects = env.Object(target = 'build/objects/Main',
                          source = ['SimpleGLExampleTest-gen.cpp'],
                          CPPPATH = ['../../include',
                                     '../../googletest-release-1.8.0/googletest/include',
                                     '../../freeglut-MSVC-3.0.0-2.mp/freeglut/include'])

env.Program(target = 'SimpleGLExampleTests',
            source = [test_objects, example_lib],
            LIBS = ['../../googletest-release-1.8.0/googletest/Release/gtest.lib',
                    '../../googletest-release-1.8.0/googletest/Release/gtest_main.lib',
                    '../../freeglut-MSVC-3.0.0-2.mp/freeglut/lib/x64/freeglut.lib'])